export enum PizzaTypesEnum {
  PEPPERONI = "Pepperoni",
  GREEK = "Greek",
  CHEESE = "Cheese",
  NY_STYLE_CHEESE = "New York Style Cheese",
  NY_STYLE_CLAM = "New York Style Clam",
  NY_STYLE_PEPPERONI = "New York Style Pepperoni",
  NY_STYLE_VEGGIE = "New York Style Veggie",
  CHICAGO_STYLE_CHEESE = "Chicago Style Cheese",
  CHICAGO_STYLE_CLAM = "Chicago Style Clam",
  CHICAGO_STYLE_PEPPERONI = "Chicago Style Pepperoni",
  CHICAGO_STYLE_VEGGIE = "Chicago Style Veggie",
  CALIFORNIA_STYLE_CHEESE = "California Style Cheese",
  CALIFORNIA_STYLE_CLAM = "California Style Clam",
  CALIFORNIA_STYLE_PEPPERONI = "California Style Pepperoni",
  CALIFORNIA_STYLE_VEGGIE = "California Style Veggie",
}
